language: ruby
install: bundle --without local_development --jobs=3 --retry=3
cache: bundler
rvm:
  - 2.4
  - 2.5
  - 2.6

gemfile:
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/activerecord_5_2.gemfile

matrix:
   exclude:
     - rvm: 2.4
       gemfile: gemfiles/rails_4_2.gemfile
     - rvm: 2.5
       gemfile: gemfiles/rails_4_2.gemfile
