language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6

gemfile:
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_5_1.gemfile

matrix:
   exclude:
     - rvm: 2.4
       gemfile: gemfiles/rails_4_0.gemfile
     - rvm: 2.4
       gemfile: gemfiles/rails_4_1.gemfile
     - rvm: 2.5
       gemfile: gemfiles/rails_4_0.gemfile
     - rvm: 2.5
       gemfile: gemfiles/rails_4_1.gemfile
     - rvm: 2.6
       gemfile: gemfiles/rails_4_0.gemfile
     - rvm: 2.6
       gemfile: gemfiles/rails_4_1.gemfile